name: Python code checks

on:
  push:
    branches-ignore:
      - "demo-gifs"
      - "samples"
  pull_request:
    branches-ignore:
      - "demo-gifs"
      - "samples"

jobs:
  formatting-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Black formatting check
        uses: psf/black@stable
        with:
          options: "--check --verbose --diff --color"

      - name: isort formatting check
        uses: isort/isort-action@master
        with:
          configuration: "--check-only --verbose --diff --color --profile black"

  pytest:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: poetry install

      - name: Build taisun
        uses: PyO3/maturin-action@v1
        with:
          command: develop
          args: --release

      - name: Run Pytest
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        run: |
          poetry run pytest --cov=./

      - name: Send coverage data to Codecov
        uses: codecov/codecov-action@v1
        if: matrix.os == 'ubuntu-latest'
